### ISSUE TITLE
건물을 자원이 부족해서 살 수 없다는 걸 알려주세요

### ISSUE THREAD

**Issue by helloheesu** [jwvg0425/MonsterFactory#16]
구매버튼이 희미해진다던가..

**Comment by ybin0823** [comment]
공갑합니다~ 좀 어려울 수 있으나 자원이 가능해지면 버튼이 활성화 되면 더 좋을 것 같네요. 자원이 모자랄 때는 버튼이 콜로니처럼 희미해지면 좋겠어요

**Comment by jwvg0425** [comment]
근데 이거 제가 지금 만들어놓은 시스템에서는 버튼이 비활성화되어있을 때에는 툴팁도 안 뜨거든요. 비활성화일 때도 툴팁이 뜨게 만드는 대신에 조건이 만족되지 않으면 버튼 모양만 비활성화되도록 해도 괜찮을까요?

**Comment by ybin0823** [comment]
툴팁이 옆에 뜨는 글짜를 말씀하는 거지요? 저는 그것보다는 버튼이 비활성되는게 눈에 확 들어오는 것 같아요.

**Comment by jwvg0425** [comment]
그런데 툴팁이 안보이면 해당 버튼의 자원이 얼마나 필요한 지 확인을 못하니, 비활성화 되어있을 때 내가 뭘 해야 이 행동을 할 수가 있지? 라는 생각이 들 거 같아서요. 그러니까 버튼 자체는 비활성화시키되(조건을 만족 못 시키면) 툴팁은 보여줘서 내가 이렇게 하면 이 버튼을 쓸 수 있겠구나 하는 건 알려줘야하지 않을까 하는거죠.

**Comment by jwvg0425** [comment]
아니면 자원이 부족하거나 한 경우 버튼을 눌렀을 때 옆에 "자원이 부족합니다" 같은 문구를 빨간색으로 띄워주는건 어떤가요

**Comment by ybin0823** [comment]
네 그게 좋은 것 같습니다. 자원이 부족합니다 라는 문구가 뜨면 좋겠네요 b
