### ISSUE TITLE
납치라는 표현보다는 다른 표현이 좋지 않나요?

### ISSUE THREAD

**Issue by ybin0823** [jwvg0425/MonsterFactory#18]
지극히 개인적인 의견입니다만, 납치/노예라는 표현 보다는 다른 표현이 낫지 않을까 생각해봅니다.

개인적으로는 고용/직원  이라던가. 그런쪽이 좀 더 거부감이 덜 들 것 같아요.

**Comment by jwvg0425** [comment]
일부러 그런 표현을 썼습니다. 개념상 사람 <-> 몬스터 구도에서 몬스터를 제공하는 공장을 운영하는 설정이기 때문에 몬스터 입장에서의 표현입니다. 몬스터가 사람을 고용하는건 조금 이상할 것 같아요. 약간 비윤리적이고 비도덕적인 게 컨셉입니다 ㅎㅎ

**Comment by ybin0823** [comment]
아. 몬스터 입장에서였군요. 이해했습니다 ㅎㅎ
