### ISSUE TITLE
몬스터 활동에 따른 경험치(?)가 표시되면 좋겠습니다.

### ISSUE THREAD

**Issue by ybin0823** [jwvg0425/MonsterFactory#19]
골드와 노예를 사용하는 활동이 더 많은 게이지를 올릴 것 같긴한데, 이 부분이 명시적으로 표시되면 좋을 것 같습니다~

마우스 hover시 각 활동에 따른 경험치가 얼마나 차는지 알 수 있으면 유용할 것 같네요

**Comment by jwvg0425** [comment]
사실 버튼 3개 효율간의 차이는 없습니다 ㅎㅎ 아직 기획이 다 안 끝났어요. 각 행동들이 어떤 영향을 끼치게 할 지 좀 고민중입니다. 그리고 각각의 행동들이 끼치는 영향을 안 가르쳐주고 플레이어가 플레이하면서 스스로 알아가도록 만들려고 했는데, 그것보다 버튼에 직접 무슨 영향을 끼치는지 적어주는 편이 나을까요? 몬스터를 계속 키워서 파는게 컨셉이다보니 여러 번 키우면서 이렇게 이렇게 키우면 되겠다 하는식으로 점점 감을 잡아가도록 만드는게 원래 제 의도였어요.

**Comment by ybin0823** [comment]
어려운 부분이네요. RPG로 생각해봐도 각각 행동들이 몬스터들의 공/방/체 등의 능력치를 다르게 준다면 이것을 숨겨서 유저가 알아가게 하는 방법도 있을 수 있고, 각각의 능력치를 알려주되 어떻게 키울지 방향을 정하는 것만 권장할 수도 있는데 기획의 부분이라 어떻게 말해야할지 모르겠네요~ 

개인적으로는 전체 게이지가 0/10294  로 표시되고 각 능력을 누르면 790/10294 로 표시되면 좋을 것 같구요. 행동에 따른 몬스터의 능력치도 표시되면 좋지 않을까요? (어떤 능력이 향상된다.) 이런식으로요

**Comment by jwvg0425** [comment]
~~가 향상된다 정도의 이야기는 해주되 세부적인 사항은 숨기고 알려지지 않은 스탯같은 걸 두는게 제 취향이라 이 방향으로 기획을 잡겠습니다. 아예 안 가르쳐주는건 너무 막막할 것 같고 다 가르쳐주는 건 제 취향에 안 맞아서요 ㅎㅎ 피드백 감사합니다.

**Comment by ybin0823** [comment]
네 좋은 것 같습니다. 너무 막연한 것보다는 무엇이 향상 되는지는 알려주는 것이 사용자가 기호에 맞게 선택할 수 있을 것 같네요. 숨겨진 스탯이 있는 것도 좋은 시스템인 것 같습니다 b
